### ISSUE TITLE
Build failure on 10.13.5: cannot find protocol declaration for 'MLCustomModel'

### ISSUE THREAD

**Issue by gustavla** [apple/turicreate#645]
I just tried a fresh source build on macOS 10.13.5 with Xcode 9.3 and I get this:
```
./turicreate/src/objc/TuriCreateObjC.h:21:37: error: cannot find protocol declaration for 'MLCustomModel'; did you mean 'MLCustomLayer'?
@interface TCRecommender : NSObject<MLCustomModel>
                                    ^~~~~~~~~~~~~
                                    MLCustomLayer
```
It looks like we're missing a 10.14+ check for the recommender.

**Comment by znation** [comment]
Looking into this.

**Comment by nickjong** [comment]
Fixed by #675
