### ISSUE TITLE
capi_sframe.cxxtest failures comparing nan values

### ISSUE THREAD

**Issue by znation** [apple/turicreate#865]
Repro steps:
1. Run debug/test/capi/capi_sframe.cxxtest

Expected:
Passes (or hangs or gives expected failures, due to #672)

Actual:
```
../test/capi/capi_utils.hpp:265: error: in "test_sframe_groupby_random_sframe_quantiles": check (column_sf[i]) == (column_ref[i]) has failed [[nan nan] != [nan nan]]
```

**Comment by TobyRoseman** [comment]
Running `ctest  capi_sframe.cxxtest` passes in master.
