### ISSUE TITLE
Error image_classifier 

### ISSUE THREAD

**Issue by kuri54** [apple/turicreate#1866]
python==3.6
turicreate ==5.5

**model = tc.image_classifier.create(train_data, target='label', max_iterations = 20)**
```
Analyzing and extracting image features.+------------------+--------------+------------------+| Images Processed | Elapsed Time | Percent Complete |+------------------+--------------+------------------+| 17               | 201.509ms    | 100%             |+------------------+--------------+------------------+Logistic regression:--------------------------------------------------------Number of examples          : 17Number of classes           : 2Number of feature columns   : 1Number of unpacked features : 2048Number of coefficients      : 2049Starting L-BFGS--------------------------------------------------------+-----------+----------+-----------+--------------+-------------------+| Iteration | Passes   | Step size | Elapsed Time | Training Accuracy |+-----------+----------+-----------+--------------+-------------------+| 0         | 5        | 0.087556  | 0.093392     | 0.647059          || 1         | 8        | 0.437780  | 0.168217     | 1.000000          || 2         | 10       | 0.437780  | 0.224214     | 1.000000          || 3         | 12       | 0.437780  | 0.280424     | 1.000000          || 4         | 14       | 0.437780  | 0.338020     | 1.000000          || 9         | 24       | 2.188902  | 0.613863     | 1.000000          || 10        | 25       | 2.188902  | 0.650273     | 1.000000          |+-----------+----------+-----------+--------------+-------------------+

not print end

**metrics = model.evaluate(test_data)**

Analyzing and extracting image features.+------------------+--------------+------------------+| Images Processed | Elapsed Time | Percent Complete |+------------------+--------------+------------------+| 3                | 33.97ms      | 100%             |+------------------+--------------+------------------+---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-35d60d25a578> in <module>
----> 1 metrics = model.evaluate(test_data)

~/turicreate/venv/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py in evaluate(self, dataset, metric, verbose, batch_size)
    798         vectors = map(lambda l: {'name': l, 'pos':list(sf_conf_mat[sf_conf_mat['target_label']==l].sort('predicted_label')['norm_prob'])},
    799                     labels)
--> 800         evaluation_result['sorted_labels'] = hclusterSort(vectors, l2Dist)[0]['name'].split("|")
    801 
    802         # Get recall and precision per label

~/turicreate/venv/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py in hclusterSort(vectors, dist_fn)
    752                     distances.append({'from': v, 'to': new_vec, 'dist': total/len(v.get('members', [v]))/len(new_vec['members'])})
    753 
--> 754                 vecs.append(new_vec)
    755                 distances = sorted(distances, key=lambda d: d['dist'])
    756 

AttributeError: 'filter' object has no attribute 'append'
```
Help me・・・

**Comment by znation** [comment]
@abhishekpratapa Looks like this got broken (in Python 3 only?) by the changes in evaluation to support image similarity. Let's make sure it gets fixed in 5.6 -- I think this is a regression from previous releases.

@kuri54 I would suggest trying Turi Create 5.3 or 5.4 -- I think this bug is relatively new, and those versions may unblock you.

**Comment by kuri54** [comment]
I try version 5.4
-> error : 'map' object・・・ #1510 This bug fixed Turi Create 5.5

It works fine with python 2.7, so it seems to be an event specific to python 3.x.
Maybe because the output of 'map' or 'filter' is no 'list'

Other try:I fixed
~/turicreate/venv/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py
line 744
vecs = filter(lambda v: v['name'] not in excluding_names, vecs)
->vecs = list(filter(lambda v: v['name'] not in excluding_names, vecs))

line 745
distances = filter(lambda dist: (dist['from']['name'] not in excluding_names) and (dist['to']['name'] not in excluding_names), distances)
->distances = list(filter(lambda dist: (dist['from']['name'] not in excluding_names) and (dist['to']['name'] not in excluding_names), distances))

It worked somehow with this・・・. Hope to be fixed in 5.6.
I want to work with version 5.4 or higher to use the annotation tool turicreate.image_classifier.annotate).

Sorry for bad english

**Comment by znation** [comment]
Sorry about that @kuri54! We'll make sure this is fixed in 5.6.

**Comment by kuri54** [comment]
Thanks！
Looking forward to Version 5.6.

**Comment by Mohsenkhodadadzadeh** [comment]
> I try version 5.4
> -> error : 'map' object・・・ #1510 This bug fixed Turi Create 5.5
> 
> It works fine with python 2.7, so it seems to be an event specific to python 3.x.
> Maybe because the output of 'map' or 'filter' is no 'list'
> 
> Other try:I fixed
> ~/turicreate/venv/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py
> line 744
> vecs = filter(lambda v: v['name'] not in excluding_names, vecs)
> ->vecs = list(filter(lambda v: v['name'] not in excluding_names, vecs))
> 
> line 745
> distances = filter(lambda dist: (dist['from']['name'] not in excluding_names) and (dist['to']['name'] not in excluding_names), distances)
> ->distances = list(filter(lambda dist: (dist['from']['name'] not in excluding_names) and (dist['to']['name'] not in excluding_names), distances))
> 
> It worked somehow with this・・・. Hope to be fixed in 5.6.
> I want to work with version 5.4 or higher to use the annotation tool turicreate.image_classifier.annotate).
> 
> Sorry for bad english

I have the same , and when I downgraded turicreate version to 5.4 I'd got this error.
So I should wait and looking forward to Version 5.6 ? :)

**Comment by kuri54** [comment]
In the case of 5.4 and 5.5, it will work normally if the corresponding file is corrected. It works correctly with 5.1 if there is no particular attention.

**Comment by srikris** [comment]
@kuri54 This has been fixed in 5.5.1 and released today. Thanks for reporting it!
