### ISSUE TITLE
Build failures on master

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#996]
On macOS 10.14:
```
/Users/zach/builds/4f04be8b/0/turi/turicreate/src/capi/impl/capi_error_handling.cpp:7:
In file included from /Users/zach/builds/4f04be8b/0/turi/turicreate/src/capi/impl/capi_error_handling.hpp:9:
In file included from /Users/zach/builds/4f04be8b/0/turi/turicreate/src/capi/impl/capi_wrapper_structs.hpp:10:
/Users/zach/builds/4f04be8b/0/turi/turicreate/src/unity/lib/variant.hpp:11:10: fatal error: 'boost/variant.hpp' file not found
#include <boost/variant.hpp>
         ^~~~~~~~~~~~~~~~~~~
```

Also repros on linux

Introduced by #972
