### ISSUE TITLE
Extend support to MXNet 1.2

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#670]

**Comment by znation** [comment]
We would need to test the mxnet 1.2 dependency across all toolkits that use mxnet: style transfer, activity classifier, object detector, etc.

**Comment by gustavla** [comment]
MXNet 1.2 breaks things seemingly unrelated to MXNet, such as an SFrame apply. I will try to produce a minimal reproducing example for this and post it here.

**Comment by shreyasvj25** [comment]
MXNet 1.2+ works fine on Mac for style transfer, 
but TuriCreate lambda workers are not compatible with Ubuntu (CPU, GPU)

**Comment by dustturtle** [comment]
what is the relationship between mxnet and turicreate?

**Comment by znation** [comment]
@dustturtle Turi Create uses mxnet under the hood for several tasks that involve deep learning: activity classification, object detection, image classification, and style transfer.

To clarify @shreyasvj25's statement above, the situation here is that:

* mxnet 1.2+ by itself seems to be fine,
* Turi Create with mxnet 1.1 and prior work just fine,
* But on Linux, Turi Create's lambda workers (`.apply` methods, used both directly by users and within the implementation of various tasks) are broken by the presence of mxnet 1.2. We're still trying to determine why/how.

**Comment by yousifKashef** [comment]
Why not allow us to downgrade to 1.0, or upgrade to 1.3 until this is resolved. I tried updating MXNet to 1.3 and I got this error message:

turicreate 5.0b1 has requirement mxnet<1.2.0,>=1.1.0, but you'll have mxnet 1.3.0.post0 which is incompatible.

I'm wondering if there's a way to change the requirement without breaking anything

**Comment by gustavla** [comment]
@yousifKashef I believe this is only a warning Pip gives you. Turi Create will also give you a run-time warning. However, as far as I know they don't stop you from upgrading to MXNet 1.3 and giving it a go. We can't guarantee that it will work, but we're interested to hear your experience with it.

**Comment by yousifKashef** [comment]
@gustavla I upgraded to MXNet 1.3 and ran my object detector script again, I got this error:

(venv) Yousifs-iMac:training yousif$ python train.py
WARNING: You are using MXNet 1.3.0 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

Using 'image' as feature column
Using 'annotations' as annotations column
Setting 'batch_size' to 16
Using GPU to create model (AMD Radeon R9 M380)
Setting 'max_iterations' to 5000
WARNING: You are using MXNet 1.3.0 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

WARNING: You are using MXNet 1.3.0 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

WARNING: You are using MXNet 1.3.0 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

WARNING: You are using MXNet 1.3.0 which may result in breaking behavior.
         To fix this, please install the currently recommended version:

             pip uninstall -y mxnet && pip install mxnet==1.1.0

         If you want to use a CUDA GPU, then change 'mxnet' to 'mxnet-cu90' (adjust 'cu90' depending on your CUDA version):

Traceback (most recent call last):
  File "train.py", line 16, in <module>
    model = tc.object_detector.create(train_data)
  File "/Users/yousif/venv/lib/python2.7/site-packages/turicreate/toolkits/object_detector/object_detector.py", line 389, in create
    ref_model.available_parameters_subset(net_params).load(ref_model.model_path, ctx)
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/gluon/parameter.py", line 902, in load
    for k, v in ndarray.load(filename).items()]
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/Users/yousif/venv/lib/python2.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:25:30] src/ndarray/ndarray.cc:1755: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000113e10b90 libmxnet.so + 15248
[bt] (1) 1   libmxnet.so                         0x0000000113e1093f libmxnet.so + 14655
[bt] (2) 2   libmxnet.so                         0x0000000113e10569 libmxnet.so + 13673
[bt] (3) 3   libmxnet.so                         0x000000011542ce94 MXNDListFree + 1451604
[bt] (4) 4   libmxnet.so                         0x000000011528208f MXNDArrayLoad + 255
[bt] (5) 5   _ctypes.so                          0x000000010c36c5c7 ffi_call_unix64 + 79
[bt] (6) 6   ???                                 0x00007ffee419cc80 0x0 + 140732725316736

**Comment by yousifKashef** [comment]
Since updating to 5.0, it always seems to crash at the line where I call the create() method in. What can I do to fix it? I first had this problem on my iMac but I thought it was the hardware. I then tried running it on my MacBook air and got the exact same error message

**Comment by yousifKashef** [comment]
I stopped getting this bug when I downgraded by 2015 iMac to high Sierra. This bug must have something to do with the GPU support in Mojave. I hope this helps. Thanks

**Comment by zm030215** [comment]
I am using cuda 10 and turicreate, I have some issue which is called: " AttributeError: module 'mxnet' has no attribute 'model'. I am using python 3.6. I having a feeling that something wrong to connect turicreate with the right version of mxnet. Any ideas?

**Comment by romanoss** [comment]
@znation 
I use turicreate 5.4 in colab for style transfer experiments in this way:

# Install libraries - you might need to restart the runtime after doing this
!pip install turicreate==5.4
# The wrong version of mxnet will be installed
!pip uninstall -y mxnet
# Install CUDA10-compatible version of mxnet
!pip install mxnet-cu100==1.4.0.post

and I can do my training there - so maybe using 1.4.0.post0 can be a solution

Maybe a younger version of tc will work too

**Comment by TobyRoseman** [comment]
@shreyasvj25 & @gustavla - how were the lambda workers not working? Were they totally broken or was the issue more subtle?

**Comment by MaximBazarov** [comment]
Gives me this on turicreate 5.6 
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-8b92b0b60ed5> in <module>()
     11 images = tc.load_sframe('./2cards.sframe')
     12 
---> 13 model = tc.one_shot_object_detector.create(images, 'label')
     14 
     15 model.export_coreml('./grn_osod.mlmodel')

3 frames
/usr/local/lib/python3.6/dist-packages/turicreate/toolkits/_mxnet/__init__.py in __getattribute__(self, attr)
     23             recommended_version_str = '1.1.0'
     24             if not (lowest_version <= version_tuple < not_yet_supported_version):
---> 25                 print('WARNING: You are using MXNet', _mx.__version__, 'which may result in breaking behavior.')
     26                 print('         To fix this, please install the currently recommended version:')
     27                 print()

NameError: name '_mx' is not defined
```

**Comment by TobyRoseman** [comment]
@MaximBazarov - That issue is already fixed in master by #2067. The fix will be included in our next release. Until then you could work around this issue by editing that locally installed file, changing `_mx.` to `mxnet.` Making sure you have the right version of MXNet installed would also solve this problem (`pip install "mxnet==1.1.0"`).

**Comment by MaximBazarov** [comment]
@TobyRoseman yeah I was about to "contribute" but then have seen that it's already there.

Unfortunately `MXNet 1.1.0` doesn't exist for CUDA92, so I'll wait the next release or will do this trick
>editing that locally installed file, changing _mx. to mxnet.
thank you!

**Comment by MaximBazarov** [comment]
Can confirm, works with 5.7, gives warning, but works (CUDA 10.0)

**Comment by rhcpfan** [comment]
> Can confirm, works with 5.7, gives warning, but works (CUDA 10.0)

Are you sure that it runs on the GPU instead of the CPU?

**Comment by srikris** [comment]
@nickjong Closing this since we are moving to TF.
