### ISSUE TITLE
Show() not working in master

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#585]
```python
In [1]: import turicreate as tc

In [2]: sa = tc.SArray(range(10))

In [3]: sa.show()
Materializing SArray...
Done.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-31c1af3e499c> in <module>()
----> 1 sa.show()

/Users/tobyroseman/Documents/turicreate/debug/src/unity/python/turicreate/data_structures/sarray.pyc in show(self, title, xlabel, ylabel)
   2940         returned_plot = self.plot(title, xlabel, ylabel)
   2941 
-> 2942         returned_plot.show()
   2943 
   2944     def plot(self, title=None, xlabel=None, ylabel=None):

/Users/tobyroseman/Documents/turicreate/debug/src/unity/python/turicreate/visualization/_plot.pyc in show(self)
    113                      raise NotImplementedError('Visualization is currently supported only on macOS and Linux.')
    114 
--> 115                 self.__proxy__.get('call_function', {'__function_name__': 'show'})
    116 
    117     def save(self, filepath):

AttributeError: 'turicreate.cython.cy_model.UnityModel' object has no attribute 'get'

In [4]: sf = tc.SFrame({'foo': sa})

In [5]: sf.show()
Materializing SFrame...
Done.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9d778c121b4c> in <module>()
----> 1 sf.show()

/Users/tobyroseman/Documents/turicreate/debug/src/unity/python/turicreate/data_structures/sframe.pyc in show(self)
   4452         returned_plot = self.plot()
   4453 
-> 4454         returned_plot.show()
   4455 
   4456     def plot(self):

/Users/tobyroseman/Documents/turicreate/debug/src/unity/python/turicreate/visualization/_plot.pyc in show(self)
    113                      raise NotImplementedError('Visualization is currently supported only on macOS and Linux.')
    114 
--> 115                 self.__proxy__.get('call_function', {'__function_name__': 'show'})
    116 
    117     def save(self, filepath):

AttributeError: 'turicreate.cython.cy_model.UnityModel' object has no attribute 'get'
```

This works fine in the latest release (4.3.2).

**Comment by shantanuchhabra** [comment]
Fixed by #594
