### PR TITLE
fix build on 10.14

### PR DESCRIPTION
**Pull request by guihao-liang**
trivial

### CODE REVIEW

**Comment by guihao-liang** [comment]
```
./src/ml/neural_net/mps_graph_trainer.mm:83:3: error: use of undeclared identifier 'log_and_throw'
  log_and_throw("Can't construct GPU Style Transfer Network for MacOS \
```
